spring.application.name=api-gateway

server.port=8765
server.instance.hostname=localhost

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=terminal_route
spring.cloud.gateway.routes[0].uri=lb://terminal
#spring.cloud.gateway.routes[0].predicates[0]=Path=/terminals/test
#spring.cloud.gateway.routes[0].predicates[1]=Method=GET
spring.cloud.gateway.routes[0].predicates[0]=Path=/terminals/**
#spring.cloud.gateway.routes[0].filters[0]=RewritePath=/terminals/(?<segment>.*), /$\{segment}

spring.cloud.gateway.routes[1].id=contract_route
spring.cloud.gateway.routes[1].uri=lb://contract
spring.cloud.gateway.routes[1].predicates[0]=Path=/contracts/**
#spring.cloud.gateway.routes[1].filters[0]=RewritePath=/contracts/(?<segment>.*), /$\{segment}

spring.cloud.gateway.globalcors.cors-configurations.'[/**]'.allowed-origins[0]="*"
spring.cloud.gateway.globalcors.cors-configurations.'[/**]'.allowed-methods[0]="*"
spring.cloud.gateway.globalcors.cors-configurations.'[/**]'.allowed-headers[0]="*"

spring.cloud.gateway.default-filters.DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
